// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;

namespace CringOMeter.Wasm.Shared
{
    public partial class CringeModel
    {
        /// <summary>
        /// model input class for CringeModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"col0")]
            public string Col0 { get; set; }

            [ColumnName(@"col1")]
            public bool Col1 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for CringeModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public bool Prediction { get; set; }

            public float Score { get; set; }

            // The probability calculated by calibrating the score of having true as the label.
            public float Probability { get; set; }
        }

        #endregion

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(Stream model, ModelInput input)
        {
            MLContext mlContext = new();

            // Load model & create prediction engine

            ITransformer mlModel = mlContext.Model.Load(model, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

            ModelOutput result = predEngine.Predict(input);
            return result;
        }
    }
}
